### PR TITLE
Fix small typos in lab naming for Git Workshop

### PR DESCRIPTION
**Pull request by aidenkeating**
This change fixes small typos in the naming of the Git Workshop books.

This also adds .DS_Store files to the .gitignore file as they
should not be committed if they are generated for any reason.

### CODE REVIEW

**Comment by aidenkeating** [comment]
@edeleastar @grdryn Just a small change to the naming of the books, mind taking a look?

**Review by grdryn — APPROVED** [review]
Looks good to me! :+1:

**Comment by aidenkeating** [comment]
@grdryn Updated the name of the second book to Advanced, have included an image below.

screen shot 2018-06-12 at 14 35 36

**Comment by grdryn** [comment]
@aidenkeating even better! :)

**Pull request merged**
